name: therm

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  macos-x64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        make -j4 CIFLAGS='CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO'
    - name: packaging
      run: make dist
    - uses: actions/upload-artifact@v3
      with:
        name: Therm.zip
        path: Therm-*.zip

